#!/bin/bash

if [ -f /opt/custom_run ]; then
    chmod u+x /opt/custom_run
    echo "=>executing /opt/custom_run"
    /opt/custom_run
fi

# Execute setup scripts
/opt/setup/influxdb
/opt/setup/grafana

# Execute Supervisord
/usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n &
trap "supervisorctl shutdown && wait" SIGTERM
wait
